on:
  workflow_dispatch:
    inputs:
      name:
        description: 'List JDK uris at https://jdk.java.net/{NAME}/'
        required: false
        type: string

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: java --show-version src/ListOpenJavaDevelopmentKits.java ${{ github.event.inputs.name }}
