on:
  workflow_dispatch:

jobs:
  features:
    name: "JDK ${{ matrix.feature }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        feature: [ 19, 18, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        id: setup
        uses: ./
        with:
          website: java.net
          feature: ${{ matrix.feature }}
      - name: 'Print outputs'
        shell: bash
        run: |
          echo 'Outputs'
          echo "steps.setup.outputs.archive = ${{ steps.setup.outputs.archive }}"
          echo "steps.setup.outputs.version = ${{ steps.setup.outputs.version }}"
      - name: 'Print Java version'
        run: java -version

  projects:
    name: "Project ${{ matrix.project }} on ${{ matrix.os }}"
    needs: [ features ]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        project: [ Loom, Panama, Valhalla ]
        exclude:
          - { os: macos-latest, project: Valhalla } # missing 'libjli.dylib'
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        id: setup
        uses: ./
        with:
          website: java.net
          feature: ${{ matrix.project }}
      - name: 'Print outputs'
        shell: bash
        run: |
          echo 'Outputs'
          echo "steps.setup.outputs.archive = ${{ steps.setup.outputs.archive }}"
          echo "steps.setup.outputs.version = ${{ steps.setup.outputs.version }}"
      - name: 'Print Java version'
        run: java -version
